#
Exploring projects on GitHub / Finding open source projects on GitHub
Finding open source projects on GitHub

You can find new and interesting open source projects to work on by browsing Explore, looking through recommended projects, connecting with the GitHub community, and searching for repositories by topics or labels.
Discovering the GitHub community

Use Explore to browse collections of curated content related to a particular field, find curated topic pages, and stay up-to-date with currently trending repositories.

You can also sign up for the Explore newsletter to receive emails about recently trending repositories.

You can connect with developers around the world in the GitHub Community Forum to ask and answer questions, learn, and interact directly with GitHub staff.
